name: Deploy All Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy all functions
        run: |
          # Iterate over all function directories and deploy
          for dir in $(find supabase/functions -mindepth 1 -maxdepth 1 -type d); do
            # Skip directories starting with "_"
            if [[ $(basename $dir) == _* ]]; then
              echo "Skipping function: $(basename $dir)"
              continue
            fi
            function_name=$(basename $dir)
            echo "Deploying function: $function_name"
            supabase functions deploy $function_name --project-ref $PROJECT_ID
          done
